version: "3.9"

services:
  review-engine:
    build: ../services/review-engine
    environment:
      - REDIS_URL_DOCKER=${REDIS_URL_DOCKER}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_SECRET=${GITHUB_SECRET}
    env_file:
      - .env
    depends_on:
      - redis

  webhook-listener:
    build: ../services/webhook-listener
    ports:
    - "8000:8000" # Expose port 8000 for the webhook listener
    environment:
      - REDIS_URL_DOCKER=${REDIS_URL_DOCKER}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_SECRET=${GITHUB_SECRET}
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
