
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/webhook-listener/requirements.txt
          pip install -r services/review-engine/requirements.txt
          pip install -r cli/requirements.txt || true
      

      - name: Run tests
        run: pytest
        env:
          REDIS_URL_DOCKER: redis://localhost:6379/0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_SECRET: ${{ secrets.GITHUB_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}